const GET_DATA = 'GET_DATA';
const SET_DATA = 'SET_DATA';
const GET_PRODUCTS = 'GET_PRODUCTS';
const SET_CURRENT_SUBLEVEL = 'SET_CURRENT_SUBLEVEL';
const GET_CURRENT_SUBLEVEL = 'GET_CURRENT_SUBLEVEL';
const MODIFY_CART = 'MODIFY_CART';
const SET_CURRENT_PRODUCT_ID = 'SET_CURRENT_PRODUCT_ID';
const SET_FAVORITE = 'SET_FAVORITE';
const GET_PRODUCT_DETAIL_BY_ID = 'GET_PRODUCT_DETAIL_BY_ID';
const CHECK_PRODUCT = 'CHECK_PRODUCT';

export {
    GET_DATA,
    SET_DATA,
    GET_PRODUCTS,
    SET_CURRENT_SUBLEVEL,
    GET_CURRENT_SUBLEVEL,
    MODIFY_CART,
    SET_CURRENT_PRODUCT_ID,
    SET_FAVORITE,
    GET_PRODUCT_DETAIL_BY_ID,
    CHECK_PRODUCT,
};
